######################################################################
# Automatically generated by qmake (1.07a) Wed Jan 16 14:20:16 2008
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
