######################################################################
# Automatically generated by qmake (2.01a) Tue May 12 20:21:04 2009
######################################################################

TEMPLATE = app
QT += network
CONFIG += release
TARGET =
LIBS += -lsqlite3
DEPENDPATH += .
INCLUDEPATH += . \
               ../kernel/

# Input
HEADERS += Storage.h StorageManager.h ../kernel/Message.h
SOURCES += Storage.cpp StorageManager.cpp main.cpp ../kernel/Message.cpp
